alertmanager:
  enabled: false
prometheus:
  prometheusSpec:
    service:
      type: LoadBalancer
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: ebs-sc
          accessModes:
            - ReadWriteOnce 
          resources:
            requests:
              storage: 5Gi

grafana:
  enabled: true
  service:
    type: LoadBalancer
  admin:
    existingSecret: grafana-admin-creds # Create a Kubernetes Secret with admin credentials (check below)
    adminPassword: admin-password
    adminUser: admin-user
nodeExporter:
  service:
    type: LoadBalancer
kubeStateMetrics:
  enabled: true
  service:
    type: LoadBalancer
additionalScrapeConfigs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: 
          - node-exporter:9100
  - job_name: 'kube-state-metrics'
    static_configs:
      - targets: 
          - kube-state-metrics:8080

# kubectl create secret generic grafana-admin-creds \
#   --from-literal=admin-user=admin \
#   --from-literal=admin-password=supersecretpassword \
#   -n monitoring

# helm upgrade --install monitoring prometheus-community/kube-prometheus-stack -f values.yaml -n monitoring --create-namespace

# kubectl patch svc monitoring-kube-prometheus-prometheus -n monitoring -p '{"spec": {"type": "LoadBalancer"}}'
# kubectl patch svc monitoring-kube-state-metrics -n monitoring -p '{"spec": {"type": "LoadBalancer"}}'
# kubectl patch svc monitoring-prometheus-node-exporter -n monitoring -p '{"spec": {"type": "LoadBalancer"}}'